name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout nvbench
        uses: actions/checkout@v4
      - name: Run lint check
        run: |
          find . \( -name "*.h" -o -name "*.cpp" -o -name "*.cu" \) -exec clang-format --dry-run -Werror {} +
  CI:
    runs-on: self-hosted
    steps:
      - name: CUDA test
        run: |
          set -xe
          pwd
          nvcc --version
          nvidia-smi
          git clone http://www.github.com/xytpai/nvbench && cd nvbench
          bash build.sh standard/perf_broadcast_add.cu && ./a.out > log
          cat log
          cd .. && rm -rf nvbench
