name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout nvbench
        uses: actions/checkout@v4
      - name: Run lint check
        run: |
          clang-format --dry-run -Werror */*.h
          clang-format --dry-run -Werror */*.cpp
          clang-format --dry-run -Werror */*.cu
